version: '3.9'

services:
  api:
    build: .
    restart: always
    container_name: api-digital-bank
    depends_on:
      - db
    ports:
      - 5000:5001
    volumes:
      - ./src:/usr/digital-bank/src
      - ./.env:/usr/digital-bank/.env
    command: yarn start:dev

  redis:
    image: redis:7-bullseye
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - /redis_bank_data:/data

  db:
    container_name: db-digital-bank
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: digitalbank
    volumes:
      - .:/digital-bank/datadir
    ports:
      - '5433:5432'
    restart: always
