version: '3.9'

services:
  # api:
  #   build: .
  #   restart: always
  #   container_name: api-ngcash
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./src:/usr/ngcash/src
  #     - ./.env:/usr/ngcash/.env
  #   command: yarn start:dev

  redis:
    image: redis:7-bullseye
    restart: always
    ports:
      - 6380:6379
    volumes: 
      - /redis_data:/data

  db:
    container_name: db-ngcash
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ngcash
    volumes:
      - .:/ngcash/datadir
    ports:
      - '5433:5432'
    restart: always
