version: '3.5'

networks:
  app-ngcash:
    driver: bridge

volumes:
  postgres:

services:
  api:
    build: .
    restart: always
    container_name: api_ngcash
    networks:
      - app-ngcash
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/ngcash/src
      - ./.env:/usr/ngcash/.env
    command: yarn start:dev

  postgres:
    container_name: postgres_container
    image: postgres
    networks:
      - app-ngcash
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: westeros
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    restart: always
